#!/bin/bash

echo ""
if ! command -v brew &> /dev/null; then
  echo "Congrats on your new Mac Rob! 💻 Let's get you setup. 🎉"
else
  echo "Let's get things updated! ⬆️"
fi
echo ""


if ! command -v brew &> /dev/null; then
  echo "***********************"
  echo "*   Installing Brew   *"
  echo "***********************"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/robtarr/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
  echo ""
  exit
fi

echo "**************************"
echo "*   Installing Formula   *"
echo "**************************"

brew install \
  bat \
  caddy \
  difftastic \
  direnv \
  duf \
  exa \
  gh \
  git \
  git-extras \
  git-filter-repo \
  git-lfs \
  git-secrets \
  go \
  imagemagick \
  jq \
  mkcert \
  ngrok \
  nss \
  pure \
  shellcheck \
  tree \
  vim
echo ""

brew tap 1Password/homebrew-tap

echo "************************"
echo "*   Installing Casks   *"
echo "************************"
brew install --cask \
  1password \
  1password/tap/1password-cli \
  alfred \
  arduino \
  charles \
  docker \
  dropbox \
  figma \
  firefox \
  flotato \
  google-chrome \
  google-drive \
  gpg-suite-no-mail \
  grandperspective \
  iterm2 \
  kaleidoscope \
  karabiner-elements \
  keybase \
  microsoft-teams \
  moom \
  obs \
  postman \
  raspberry-pi-imager \
  rocket \
  setapp \
  skitch \
  slack \
  spotify \
  tableplus \
  ultimaker-cura \
  visual-studio-code \
  vlc \
  yubico-authenticator \
  zoom

brew tap homebrew/cask-fonts
brew install --cask \
  font-fira-code \
  font-fira-code-nerd-font

brew tap homebrew/cask-drivers
brew install --cask yubico-yubikey-manager
echo ""

echo "**************************************"
echo "*   I couldn't install these Casks   *"
echo "**************************************"
echo autodesk-fusion360
echo ""

echo "*********************************"
echo "*   Fix Harvest Time Format     *"
echo "*********************************"
defaults write ~/Library/Containers/com.getharvest.harvestxapp/Data/Library/Preferences/group.com.getharvest.Harvest.Documents.plist TimeFormat hours_minutes
echo ""

if [ ! -d ~/dotfiles ]; then
  echo "************************"
  echo "*   Clone Dotfiles     *"
  echo "************************"
  git clone https://github.com/robtarr/dotfiles.git ~/dotfiles
  echo ""
fi

echo "**********************"
echo "*   Setup symlinks   *"
echo "**********************"
for link in .gitconfig .gitignore .gitmessage.txt .zshrc; do
  if [ -L "$HOME/$link" ]; then
    echo "Link '$link' exists"
  else
    ln -s "$HOME/dotfiles/$link" "$HOME/$link"
  fi
done
echo ""

if [ ! nvm -v &> /dev/null ]; then
  echo "*****************"
  echo "*   Setup NVM   *"
  echo "*****************"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  echo ""
  exit
fi

if [ ! particle -v &> /dev/null ]; then
  echo "**************************"
  echo "*   Setup Particle CLI   *"
  echo "**************************"
  bash <( curl -sL https://particle.io/install-cli )
  echo ""
fi


echo "*******************************"
echo "*   Removing the dock delay   *"
echo "*******************************"
defaults write com.apple.Dock autohide-delay -float 0
killall Dock
echo ""
# To restore to default
#   defaults delete com.apple.Dock autohide-delay
#   killall Dock


if [ -d "~/.ssh" ]; then
  echo "*********************"
  echo "*   Create ~/.ssh   *"
  echo "*********************"
  mkdir ~/.ssh
  echo ""
fi

if [ -d "~/projects" ]; then
  echo "*************************"
  echo "*   Create ~/projects   *"
  echo "*************************"
  mkdir ~/projects
  echo ""
fi

if [ -d "~/my-projects" ]; then
  echo "****************************"
  echo "*   Create ~/my-projects   *"
  echo "****************************"
  mkdir ~/my-projects
  echo ""
fi

echo "****************************************"
echo "*   Here are some other things to do   *"
echo "****************************************"
echo ""
echo "Download these apps:"
echo " • Trello https://apps.apple.com/us/app/trello/id1278508951?mt=12"
echo " • Harvest https://apps.apple.com/us/app/harvest/id506189836?ls=1&mt=12"
echo " • Yubikey Manager https://www.yubico.com/support/download/yubikey-manager"
echo ""

echo " • Remove Spotlight shortcut & Setup Alfred"
echo " • Copy ssh keys"
echo " • Copy /etc/hosts"
echo " • Import iTerm profile from ~/dotfiles"
echo " • Setup moom"
echo " • Setup Karabiner"
echo " • Login to mail accounts"
echo " • Setup yubikey https://support.yubico.com/hc/en-us/articles/360016649059"
echo " • Preferences > Security & Preferences > Use Watch to unlock"

echo ""
echo ""