#!/bin/bash

echo "Congrats on your new Mac! Let's get you setup, Rob"

echo "***********************"
echo "*   Installing Brew   *"
echo "***********************"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "**************************"
echo "*   Installing Formula   *"
echo "**************************"

brew install \
  caddy \
  git \
  git-extras \
  git-secrets \
  gh \
  imagemagick \
  jq \
  shellcheck \
  vim \
  pure \
  ngrok \
  mkcert \
  nss \
  tree \
  go \
  git-filter-repo \
  direnv

echo "***************************"
echo "*   Installing Heroku CLI *"
echo "**************************"
brew tap heroku/brew && brew install heroku

echo "************************"
echo "*   Installing Casks   *"
echo "************************"
brew install --cask \
  1password \
  alfred \
  dropbox \
  harvest \
  moom \
  xbar \
  rocket \
  flotato \
  keybase \
  \
  slack \
  microsoft-teams \
  zoom \
  obs \
  recordit \
  \
  firefox \
  google-chrome \
  browserstacklocal \
  \
  iterm2 \
  docker \
  visual-studio-code \
  figma \
  sublime-text \
  kaleidoscope \
  gpg-suite-no-mail \
  \
  tweetbot \
  spotify \
  autodesk-fusion360 \
  freecad \
  ultimaker-cura \
  skitch \
  dozer \
  postman \
  tableplus \
  superfly/tap/flyctl \
  vlc \
  karabiner-elements

brew tap homebrew/cask-fonts
brew install --cask font-fira-code

echo "*********************************"
echo "*   Fox Harvest Time Format     *"
echo "*********************************"
defaults write ~/Library/Containers/com.getharvest.harvestxapp/Data/Library/Preferences/group.com.getharvest.Harvest.Documents.plist TimeFormat hours_minutes

echo "************************"
echo "*   Setup Dotfiles     *"
echo "************************"
if [ ! -d ~/dotfiles ]; then
  git clone https://github.com/robtarr/dotfiles.git ~/dotfiles
fi

mkdir -p "~/Library/Application Support/xbar/"
ln -sf "$PWD/dotfiles/xbar/plugins" "$HOME/Library/Application Support/xbar/plugins"

for link in .gitconfig .gitignore .gitmessage.txt .zshrc; do
  if [ -L "$HOME/$link" ]; then
    echo "Link '$link' exists"
  else
    ln -s "$PWD/$link" "$HOME/$link"
  fi
done

# echo "*****************"
# echo "*   Setup NVM   *"
# echo "*****************"
# NODE_VERSION=14 PROFILE=/dev/null sh -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh)"

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

echo "*************************"
echo "*   Setup Nix & Lorri   *"
echo "*************************"
sh <(curl -L https://nixos.org/nix/install)
nix-env -i lorri

echo "**************************"
echo "*   Setup Particle CLI   *"
echo "**************************"
bash <( curl -sL https://particle.io/install-cli )

echo "**********************"
echo "*   App Store Apps   *"
echo "**********************"
echo ""
echo "https://apps.apple.com/us/app/trello/id1278508951?mt=12"